"""性能测试集成模块"""
import os
import sys
import json
import time
import tempfile
import subprocess
from pathlib import Path
from typing import Dict, Any, List, Optional, Union
from dataclasses import dataclass, field
from datetime import datetime

from ..observability.logger import get_logger
from ..observability.tracer import get_tracer
from ..observability.metrics import record_test_metric

# 检查Locust是否可用
try:
    import locust
    from locust import HttpUser, task, between
    from locust.env import Environment
    from locust.stats import stats_printer, stats_history
    from locust.log import setup_logging
    LOCUST_AVAILABLE = True
except ImportError:
    LOCUST_AVAILABLE = False
    locust = HttpUser = task = between = Environment = None
    stats_printer = stats_history = setup_logging = None


@dataclass
class PerformanceTestConfig:
    """性能测试配置"""
    target_url: str
    users: int = 10
    spawn_rate: float = 1.0
    duration: int = 60
    host: Optional[str] = None
    test_name: str = "performance_test"
    output_format: str = "json"
    locustfile: Optional[str] = None
    headless: bool = True
    csv_prefix: Optional[str] = None
    html_report: Optional[str] = None
    tags: List[str] = field(default_factory=list)
    exclude_tags: List[str] = field(default_factory=list)
    custom_options: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PerformanceMetrics:
    """性能测试度量"""
    total_requests: int
    failed_requests: int
    average_response_time: float
    min_response_time: float
    max_response_time: float
    median_response_time: float
    p95_response_time: float
    p99_response_time: float
    requests_per_second: float
    failures_per_second: float
    test_duration: float
    success_rate: float
    error_rate: float
    total_data_sent: int = 0
    total_data_received: int = 0


@dataclass
class PerformanceTestResult:
    """性能测试结果"""
    test_name: str
    status: str  # success, failed, error
    start_time: datetime
    end_time: datetime
    duration: float
    config: PerformanceTestConfig
    metrics: PerformanceMetrics
    errors: List[Dict[str, Any]] = field(default_factory=list)
    raw_output: str = ""
    reports: Dict[str, str] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)


class LocustTestGenerator:
    """Locust测试脚本生成器"""
    
    def __init__(self):
        self.logger = get_logger("phoenixframe.performance.generator")
    
    def generate_basic_test(self, config: PerformanceTestConfig) -> str:
        """生成基础性能测试脚本"""
        template = f'''"""
Generated Locust performance test
Target: {config.target_url}
Generated by PhoenixFrame
"""
from locust import HttpUser, task, between
import random
import json


class {config.test_name.title().replace('_', '')}User(HttpUser):
    """Performance test user for {config.test_name}"""
    
    wait_time = between(1, 3)
    host = "{config.target_url}"
    
    def on_start(self):
        """Called when a user starts"""
        self.client.verify = False  # 忽略SSL证书验证
        
    @task(3)
    def get_home_page(self):
        """访问首页"""
        with self.client.get("/", catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Got status code {{response.status_code}}")
            else:
                response.success()
    
    @task(2)
    def get_api_health(self):
        """健康检查接口"""
        with self.client.get("/health", catch_response=True) as response:
            if response.status_code == 200:
                response.success()
            elif response.status_code == 404:
                # 404可能是正常的，取决于API设计
                response.success()
            else:
                response.failure(f"Health check failed with status {{response.status_code}}")
    
    @task(1)
    def post_data(self):
        """POST请求测试"""
        data = {{
            "test_data": random.randint(1, 1000),
            "timestamp": "{{}}".format(int(time.time()))
        }}
        
        with self.client.post("/api/test", json=data, catch_response=True) as response:
            if response.status_code in [200, 201, 404]:  # 404可能是正常的
                response.success()
            else:
                response.failure(f"POST failed with status {{response.status_code}}")
    
    @task(1)
    def simulate_user_workflow(self):
        """模拟用户工作流"""
        # 步骤1: 获取数据
        with self.client.get("/api/data", catch_response=True) as response:
            if response.status_code in [200, 404]:
                response.success()
            else:
                response.failure(f"Workflow step 1 failed")
                return
        
        # 步骤2: 处理数据
        time.sleep(random.uniform(0.1, 0.5))
        
        # 步骤3: 提交结果
        result_data = {{"result": "processed", "user_id": random.randint(1, 100)}}
        with self.client.post("/api/result", json=result_data, catch_response=True) as response:
            if response.status_code in [200, 201, 404]:
                response.success()
            else:
                response.failure(f"Workflow step 3 failed")


# 如果直接运行此文件，启动Locust
if __name__ == "__main__":
    import os
    os.system(f"locust -f {{__file__}} --host {config.target_url}")
'''
        return template
    
    def generate_api_test(self, config: PerformanceTestConfig, 
                         endpoints: List[Dict[str, Any]]) -> str:
        """生成API性能测试脚本"""
        tasks = []
        
        for i, endpoint in enumerate(endpoints):
            method = endpoint.get('method', 'GET').upper()
            path = endpoint.get('path', '/')
            weight = endpoint.get('weight', 1)
            name = endpoint.get('name', f'endpoint_{i}')
            
            if method == 'GET':
                task_code = f'''
    @task({weight})
    def {name}(self):
        """Test {method} {path}"""
        with self.client.get("{path}", catch_response=True) as response:
            if response.status_code == 200:
                response.success()
            else:
                response.failure(f"GET {path} failed with status {{response.status_code}}")
'''
            elif method == 'POST':
                task_code = f'''
    @task({weight})
    def {name}(self):
        """Test {method} {path}"""
        data = {{"test": "data", "timestamp": int(time.time())}}
        with self.client.post("{path}", json=data, catch_response=True) as response:
            if response.status_code in [200, 201]:
                response.success()
            else:
                response.failure(f"POST {path} failed with status {{response.status_code}}")
'''
            else:
                task_code = f'''
    @task({weight})
    def {name}(self):
        """Test {method} {path}"""
        with self.client.request("{method}", "{path}", catch_response=True) as response:
            if response.status_code < 400:
                response.success()
            else:
                response.failure(f"{method} {path} failed with status {{response.status_code}}")
'''
            tasks.append(task_code)
        
        template = f'''"""
Generated API Performance Test
Target: {config.target_url}
Generated by PhoenixFrame
"""
from locust import HttpUser, task, between
import time
import json
import random


class {config.test_name.title().replace('_', '')}APIUser(HttpUser):
    """API performance test user"""
    
    wait_time = between(1, 2)
    host = "{config.target_url}"
    
    def on_start(self):
        """Called when a user starts"""
        self.client.verify = False
        
{"".join(tasks)}
'''
        return template


class LocustTestRunner:
    """Locust性能测试运行器"""
    
    def __init__(self):
        self.logger = get_logger("phoenixframe.performance.runner")
        self.tracer = get_tracer("phoenixframe.performance.runner")
        self.generator = LocustTestGenerator()
    
    def run_performance_test(self, config: PerformanceTestConfig) -> PerformanceTestResult:
        """运行性能测试"""
        if not LOCUST_AVAILABLE:
            return PerformanceTestResult(
                test_name=config.test_name,
                status="error",
                start_time=datetime.now(),
                end_time=datetime.now(),
                duration=0.0,
                config=config,
                metrics=PerformanceMetrics(
                    total_requests=0,
                    failed_requests=0,
                    average_response_time=0.0,
                    min_response_time=0.0,
                    max_response_time=0.0,
                    median_response_time=0.0,
                    p95_response_time=0.0,
                    p99_response_time=0.0,
                    requests_per_second=0.0,
                    failures_per_second=0.0,
                    test_duration=0.0,
                    success_rate=0.0,
                    error_rate=0.0
                ),
                errors=[{"error": "Locust not available. Install with: pip install locust"}],
                raw_output="Locust not installed"
            )
        
        with self.tracer.trace_test_case("locust_performance_test", config.test_name, "running"):
            start_time = datetime.now()
            
            try:
                # 创建临时测试文件
                if not config.locustfile:
                    locustfile_path = self._create_temp_locustfile(config)
                else:
                    locustfile_path = config.locustfile
                
                # 运行Locust测试
                result = self._run_locust_command(config, locustfile_path)
                
                end_time = datetime.now()
                duration = (end_time - start_time).total_seconds()
                
                # 解析结果
                metrics = self._parse_locust_results(result)
                
                # 记录度量
                record_test_metric(
                    "performance_test",
                    "completed" if result["exit_code"] == 0 else "failed",
                    duration,
                    {
                        "tool": "locust",
                        "users": config.users,
                        "duration": config.duration,
                        "requests_per_second": metrics.requests_per_second,
                        "success_rate": metrics.success_rate
                    }
                )
                
                return PerformanceTestResult(
                    test_name=config.test_name,
                    status="success" if result["exit_code"] == 0 else "failed",
                    start_time=start_time,
                    end_time=end_time,
                    duration=duration,
                    config=config,
                    metrics=metrics,
                    errors=self._extract_errors(result["stderr"]),
                    raw_output=result["stdout"] + result["stderr"],
                    metadata={"command": result["command"]}
                )
                
            except Exception as e:
                end_time = datetime.now()
                duration = (end_time - start_time).total_seconds()
                
                self.logger.error(f"Performance test failed: {e}")
                return PerformanceTestResult(
                    test_name=config.test_name,
                    status="error",
                    start_time=start_time,
                    end_time=end_time,
                    duration=duration,
                    config=config,
                    metrics=PerformanceMetrics(
                        total_requests=0,
                        failed_requests=0,
                        average_response_time=0.0,
                        min_response_time=0.0,
                        max_response_time=0.0,
                        median_response_time=0.0,
                        p95_response_time=0.0,
                        p99_response_time=0.0,
                        requests_per_second=0.0,
                        failures_per_second=0.0,
                        test_duration=0.0,
                        success_rate=0.0,
                        error_rate=0.0
                    ),
                    errors=[{"error": str(e)}],
                    raw_output=str(e)
                )
    
    def _create_temp_locustfile(self, config: PerformanceTestConfig) -> str:
        """创建临时Locust文件"""
        test_code = self.generator.generate_basic_test(config)
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
            f.write(test_code)
            temp_file = f.name
        
        self.logger.info(f"Created temporary locustfile: {temp_file}")
        return temp_file
    
    def _run_locust_command(self, config: PerformanceTestConfig, locustfile: str) -> Dict[str, Any]:
        """运行Locust命令"""
        cmd = [
            sys.executable, "-m", "locust",
            "-f", locustfile,
            "--host", config.target_url,
            "--users", str(config.users),
            "--spawn-rate", str(config.spawn_rate),
            "--run-time", f"{config.duration}s",
            "--headless"
        ]
        
        # 添加输出选项
        if config.html_report:
            cmd.extend(["--html", config.html_report])
        
        if config.csv_prefix:
            cmd.extend(["--csv", config.csv_prefix])
        
        # 添加标签过滤
        if config.tags:
            cmd.extend(["--tags"] + config.tags)
        
        if config.exclude_tags:
            cmd.extend(["--exclude-tags"] + config.exclude_tags)
        
        # 添加自定义选项
        for key, value in config.custom_options.items():
            cmd.extend([f"--{key}", str(value)])
        
        self.logger.info(f"Running Locust command: {' '.join(cmd)}")
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=config.duration + 60  # 额外缓冲时间
            )
            
            return {
                "exit_code": result.returncode,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "command": " ".join(cmd)
            }
        except subprocess.TimeoutExpired:
            self.logger.error("Locust test timed out")
            return {
                "exit_code": -1,
                "stdout": "",
                "stderr": "Test timed out",
                "command": " ".join(cmd)
            }
        except Exception as e:
            self.logger.error(f"Failed to run Locust: {e}")
            return {
                "exit_code": -1,
                "stdout": "",
                "stderr": str(e),
                "command": " ".join(cmd)
            }
    
    def _parse_locust_results(self, result: Dict[str, Any]) -> PerformanceMetrics:
        """解析Locust结果"""
        # 从stdout中提取性能数据
        stdout = result.get("stdout", "")
        
        # 默认值
        metrics = PerformanceMetrics(
            total_requests=0,
            failed_requests=0,
            average_response_time=0.0,
            min_response_time=0.0,
            max_response_time=0.0,
            median_response_time=0.0,
            p95_response_time=0.0,
            p99_response_time=0.0,
            requests_per_second=0.0,
            failures_per_second=0.0,
            test_duration=0.0,
            success_rate=0.0,
            error_rate=0.0
        )
        
        # 解析Locust输出
        lines = stdout.split('\n')
        for line in lines:
            if 'requests' in line and 'failures' in line:
                # 解析请求统计行
                parts = line.split()
                for i, part in enumerate(parts):
                    if part.isdigit():
                        if 'requests' in line:
                            metrics.total_requests = int(part)
                        elif 'failures' in line:
                            metrics.failed_requests = int(part)
            elif 'RPS' in line or 'req/s' in line:
                # 解析RPS
                import re
                rps_match = re.search(r'(\d+\.?\d*)\s*(?:RPS|req/s)', line)
                if rps_match:
                    metrics.requests_per_second = float(rps_match.group(1))
            elif 'response time' in line.lower():
                # 解析响应时间
                import re
                time_match = re.search(r'(\d+\.?\d*)\s*ms', line)
                if time_match:
                    metrics.average_response_time = float(time_match.group(1))
        
        # 计算派生度量
        if metrics.total_requests > 0:
            metrics.success_rate = ((metrics.total_requests - metrics.failed_requests) / metrics.total_requests) * 100
            metrics.error_rate = (metrics.failed_requests / metrics.total_requests) * 100
        
        return metrics
    
    def _extract_errors(self, stderr: str) -> List[Dict[str, Any]]:
        """提取错误信息"""
        errors = []
        
        if stderr:
            lines = stderr.split('\n')
            for line in lines:
                if 'ERROR' in line or 'error' in line.lower():
                    errors.append({
                        "type": "runtime_error",
                        "message": line.strip(),
                        "timestamp": datetime.now().isoformat()
                    })
        
        return errors


class PerformanceTestManager:
    """性能测试管理器"""
    
    def __init__(self):
        self.logger = get_logger("phoenixframe.performance.manager")
        self.tracer = get_tracer("phoenixframe.performance.manager")
        self.runner = LocustTestRunner()
        self.generator = LocustTestGenerator()
    
    def run_performance_test(self, config: PerformanceTestConfig) -> PerformanceTestResult:
        """运行性能测试"""
        with self.tracer.trace_test_case("performance_test_suite", config.test_name, "running"):
            self.logger.info(f"Starting performance test: {config.test_name}")
            
            result = self.runner.run_performance_test(config)
            
            self.logger.info(f"Performance test completed: {config.test_name}")
            return result
    
    def generate_locustfile(self, config: PerformanceTestConfig, 
                          output_file: str, test_type: str = "basic") -> str:
        """生成Locust测试文件"""
        if test_type == "basic":
            content = self.generator.generate_basic_test(config)
        else:
            content = self.generator.generate_basic_test(config)
        
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding='utf-8')
        
        self.logger.info(f"Generated locustfile: {output_file}")
        return content
    
    def generate_performance_report(self, results: List[PerformanceTestResult],
                                  output_file: Optional[str] = None) -> str:
        """生成性能测试报告"""
        report_data = {
            "report_timestamp": datetime.now().isoformat(),
            "summary": self._generate_summary(results),
            "tests": []
        }
        
        for result in results:
            test_data = {
                "test_name": result.test_name,
                "status": result.status,
                "duration": result.duration,
                "config": {
                    "users": result.config.users,
                    "spawn_rate": result.config.spawn_rate,
                    "duration": result.config.duration,
                    "target_url": result.config.target_url
                },
                "metrics": {
                    "total_requests": result.metrics.total_requests,
                    "failed_requests": result.metrics.failed_requests,
                    "success_rate": result.metrics.success_rate,
                    "error_rate": result.metrics.error_rate,
                    "average_response_time": result.metrics.average_response_time,
                    "requests_per_second": result.metrics.requests_per_second
                },
                "errors": result.errors
            }
            report_data["tests"].append(test_data)
        
        report_json = json.dumps(report_data, indent=2, ensure_ascii=False)
        
        if output_file:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(report_json)
            self.logger.info(f"Performance report saved to: {output_file}")
        
        return report_json
    
    def _generate_summary(self, results: List[PerformanceTestResult]) -> Dict[str, Any]:
        """生成性能测试总结"""
        total_tests = len(results)
        passed_tests = len([r for r in results if r.status == "success"])
        failed_tests = len([r for r in results if r.status in ["failed", "error"]])
        
        total_requests = sum(r.metrics.total_requests for r in results)
        total_failures = sum(r.metrics.failed_requests for r in results)
        
        avg_response_time = sum(r.metrics.average_response_time for r in results) / total_tests if total_tests > 0 else 0
        avg_rps = sum(r.metrics.requests_per_second for r in results) / total_tests if total_tests > 0 else 0
        
        return {
            "total_tests": total_tests,
            "passed_tests": passed_tests,
            "failed_tests": failed_tests,
            "success_rate": (passed_tests / total_tests * 100) if total_tests > 0 else 0,
            "total_requests": total_requests,
            "total_failures": total_failures,
            "overall_success_rate": ((total_requests - total_failures) / total_requests * 100) if total_requests > 0 else 0,
            "average_response_time": avg_response_time,
            "average_rps": avg_rps
        }


# 全局性能测试管理器实例
_performance_manager: Optional[PerformanceTestManager] = None


def get_performance_manager() -> PerformanceTestManager:
    """获取性能测试管理器实例"""
    global _performance_manager
    if _performance_manager is None:
        _performance_manager = PerformanceTestManager()
    return _performance_manager


def run_performance_test(config: PerformanceTestConfig) -> PerformanceTestResult:
    """运行性能测试"""
    manager = get_performance_manager()
    return manager.run_performance_test(config)


def generate_locustfile(config: PerformanceTestConfig, output_file: str, test_type: str = "basic") -> str:
    """生成Locust测试文件"""
    manager = get_performance_manager()
    return manager.generate_locustfile(config, output_file, test_type)


def generate_performance_report(results: List[PerformanceTestResult],
                               output_file: Optional[str] = None) -> str:
    """生成性能测试报告"""
    manager = get_performance_manager()
    return manager.generate_performance_report(results, output_file)


__all__ = [
    "PerformanceTestConfig",
    "PerformanceMetrics", 
    "PerformanceTestResult",
    "LocustTestGenerator",
    "LocustTestRunner",
    "PerformanceTestManager",
    "get_performance_manager",
    "run_performance_test",
    "generate_locustfile",
    "generate_performance_report",
    "LOCUST_AVAILABLE"
]